trigger-word: "welcome"
window: 10 # seconds
reward:
  item: "GOLD_NUGGET"
  amount: 5
  sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
  message: "Thanks for welcoming a new player, you've received <yellow>5 gold nuggets</yellow> as a gift!"
